services:
  # mysql:
  #   image: 'mysql:latest'
  #   environment:
  #     - 'MYSQL_USER=mysql'
  #     - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - 'mysql_db:/var/lib/mysql'
  postgres:
    image: 'postgres:14'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_db:/var/lib/postgresql/data'
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    volumes:
      - 'rabbitmq_db:/var/lib/rabbitmq/mnesia'
volumes:
  postgres_db:
  rabbitmq_db:
  mysql_db: